apiVersion: v1
kind: PersistentVolume
metadata:
   name: local-persistent-volume-1
spec:
   capacity:
      storage: 5Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: local-storage
   local:
      path: /home/marcos/Proj/research/image-catalog/docker-registry/storage
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - kind-control-plane